[tool.poetry]
name = "web"
version = "0.1.0"
description = "Este es mi portfolio"
authors = ["Daniel Cort√©s"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
